#!/bin/bash

/var/www/minera/minera-bin/cgminer-dmaxl-zeus --scrypt --scan-serial zeus:auto --zeus-chips 128 --zeus-clock 245 -c /var/www/minera/conf/miner_conf.json 2>/var/log/minera/cgminerdmaxlzeus.log