#!/bin/bash

/var/www/minera/minera-bin/cgminer-dmaxl-zeus --sha256 --scan-serial gridseed:auto --gridseed-options freq=838 -c /var/www/minera/conf/miner_conf.json 2>/var/log/minera/cgminerdmaxlzeus.log